{{- range .Values.configs }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-hub-rate-limit-exporter.fullname" $ }}-{{ .name }}
  labels:
    {{- include "docker-hub-rate-limit-exporter.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "docker-hub-rate-limit-exporter.selectorLabels" $ | nindent 6 }}
      instance: {{ .name }}
  template:
    metadata:
      annotations:
        {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "docker-hub-rate-limit-exporter.selectorLabels" $ | nindent 8 }}
        instance: {{ .name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "docker-hub-rate-limit-exporter.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ default 80 .exporterPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 5
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          env:
            - name: DOCKERHUB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "docker-hub-rate-limit-exporter.fullname" $ }}-{{ .name }}-configmap
                  key: dockerhub-username
            - name: DOCKERHUB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "docker-hub-rate-limit-exporter.fullname" $ }}-{{ .name }}-secret
                  key: dockerhub-password
            - name: DOCKERHUB_EXPORTER_VERBOSE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "docker-hub-rate-limit-exporter.fullname" $ }}-{{ .name }}-configmap
                  key: exporter-verbosity
            - name: DOCKERHUB_EXPORTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "docker-hub-rate-limit-exporter.fullname" $ }}-{{ .name }}-configmap
                  key: exporter-port
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}