{{- $config := default dict .Values.config }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-hub-rate-limit-exporter.fullname" . }}-configmap
  labels:
    {{- include "docker-hub-rate-limit-exporter.labels" . | nindent 4 }}
data:
  exporter-port: {{ .Values.service.targetPort | quote }}
  exporter-verbosity: {{ hasKey $config "verbosity" | ternary $config.verbosity 1 | quote }}
