{{- if .Values.daemonset.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "docker-hub-rate-limit-exporter.fullname" . }}
  labels:
    {{- include "docker-hub-rate-limit-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "docker-hub-rate-limit-exporter.selectorLabels" . | nindent 6 }}
  {{- if .Values.daemonset.updateStrategy }}
  updateStrategy:
{{ toYaml .Values.daemonset.updateStrategy | indent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "docker-hub-rate-limit-exporter.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.daemonset.podAnnotations }}
        {{- toYaml .Values.daemonset.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      serviceAccountName: {{ include "docker-hub-rate-limit-exporter.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext }}
          securityContext:
{{ toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.portName }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            timeoutSeconds: {{ .Values.livenessProbeTimeoutSeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            timeoutSeconds: {{ .Values.readinessProbeTimeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DOCKERHUB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "docker-hub-rate-limit-exporter.fullname" . }}-secret
                  key: dockerhub-username
            - name: DOCKERHUB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "docker-hub-rate-limit-exporter.fullname" . }}-secret
                  key: dockerhub-password
            - name: DOCKERHUB_EXPORTER_VERBOSE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "docker-hub-rate-limit-exporter.fullname" . }}-configmap
                  key: exporter-verbosity
            - name: DOCKERHUB_EXPORTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "docker-hub-rate-limit-exporter.fullname" . }}-configmap
                  key: exporter-port
      {{- if .Values.daemonset.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.daemonset.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.daemonset.affinity }}
      affinity:
{{ toYaml .Values.daemonset.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.daemonset.tolerations }}
      tolerations:
{{ toYaml .Values.daemonset.tolerations | indent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      hostPID: {{ .Values.hostPID }}

{{- end }}
