{{- range $deploymentKey, $deployment := .Values.deployments }}
{{- if $deployment.enabled }}
{{- $config := default dict $deployment.config }}
{{- $configDockerHub := default dict $config.dockerhub }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-hub-rate-limit-exporter.fullname" $ }}-secret-{{ $deploymentKey }}
  labels:
    {{- include "docker-hub-rate-limit-exporter.labels" $ | nindent 4 }}
data:
  dockerhub-username: {{ default "" $configDockerHub.username | b64enc | quote }}
  dockerhub-password: {{ default "" $configDockerHub.password | b64enc | quote }}

---
{{- end }}
{{- end }}

{{- if .Values.daemonset.enabled }}
{{- if .Values.daemonset.config }}
{{- if .Values.daemonset.config.dockerhub }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-hub-rate-limit-exporter.fullname" . }}-secret
  labels:
    {{- include "docker-hub-rate-limit-exporter.labels" . | nindent 4 }}
data:
  dockerhub-username: {{ .Values.daemonset.config.dockerhub.username | b64enc | quote }}
  dockerhub-password: {{ .Values.daemonset.config.dockerhub.password | b64enc | quote }}

---
{{- end }}
{{- end }}
{{- end }}
