# Default values for docker-hub-rate-limit-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Commonly used for authenticated users
deployments:
    default:
        enabled: true
        replicaCount: 1
        podAnnotations: {}
        config:
            # Log level of the exporter
            verbosity: 1
            dockerhub:
                username: ""
                password: ""
        # nodeSelector:
        #     node-role.kubernetes.io/docker-hub-authenticated: "true"

# Commonly used for anonymous users
daemonset:
    enabled: true
    updateStrategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
    podAnnotations: {}
    config:
        # Log level of the exporter
        verbosity: 1
        dockerhub:
            username: ""
            password: ""
    # affinity:
    #     nodeAffinity:
    #         requiredDuringSchedulingIgnoredDuringExecution:
    #             nodeSelectorTerms:
    #                 - matchExpressions:
    #                     - key: node-role.kubernetes.io/docker-hub-authenticated
    #                       operator: NotIn
    #                       values:
    #                           - "true"


image:
    repository: viadee/docker-hub-rate-limit-exporter
    tag: ""
    pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceMonitor:
    enabled: true
    additionalLabels: {}
    namespace: ""

    jobLabel: ""

    scheme: http
    bearerTokenFile:
    tlsConfig: {}

    ## proxyUrl: URL of a proxy that should be used for scraping.
    ##
    proxyUrl: ""

    ## Override serviceMonitor selector
    ##
    selectorOverride: {}

    relabelings:
        - action: replace
          sourceLabels:
              - __meta_kubernetes_pod_node_name
          targetLabel: instance
        - action: replace
          sourceLabels:
              - __meta_kubernetes_pod_host_ip
          targetLabel: host_ip
    metricRelabelings: []
    interval: ""
    scrapeTimeout: 25s

serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

podAnnotations:
    sidecar.istio.io/inject: "false"

podSecurityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534

securityContext:
    capabilities:
        add:
            - SYS_TIME

service:
    type: ClusterIP
    port: 80
    targetPort: 80
    nodePort:
    portName: metrics
    annotations: {}

livenessProbeTimeoutSeconds: 5

readinessProbeTimeoutSeconds: 5

resources:
    limits:
        cpu: 200m
        memory: 96Mi
    requests:
        cpu: 50m
        memory: 64Mi

nodeSelector: {}

tolerations: []

priorityClassName: ""

affinity: {}

# Expose the service to the host network
hostNetwork: false

# Share the host process ID namespace
hostPID: true
